services:
  vite:
    image: node:22-alpine
    working_dir: /code
    volumes:
      - .:/code
      - vite_deps:/code/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host
  api_proxy:
    image: golang:1.25-alpine
    working_dir: /code
    volumes:
      - ./server:/code
    command: go run cmd/server/main.go

volumes:
  vite_deps:
